# Generated by Django 4.0 on 2021-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='mail_scan',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
