# Generated by Django 4.0 on 2021-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_mails_mail_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='mail_scan',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
