# Generated by Django 4.0 on 2021-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_alter_mails_mail_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='mail_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mails',
            name='mail_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mails',
            name='mail_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mails',
            name='mail_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
