# Generated by Django 4.0 on 2021-12-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
