# Generated by Django 4.0 on 2021-12-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_mails_mail_number_alter_mails_mail_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='mail_rec_date',
            field=models.DateField(null=True),
        ),
    ]
