# Generated by Django 4.0 on 2021-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_alter_mails_mail_rec_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='mail_title',
            field=models.CharField(max_length=100),
        ),
    ]
